meta_product_name: "Keyz"
meta_title: " Keyz | Investissements Locatifs"
meta_description: "Propriétaire? Evaluez la performance financière de vos biens"
meta_image: "owner_1200x630.jpg" # should exist in `app/assets/images/`